version: '3'

services:
    php:
        build:
            context: .
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"

    web:
        image: nginx:alpine
        working_dir: /var/www/html
        container_name: digi_nginx
        volumes:
            - ./:/var/www/html
            - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
        depends_on:
            - php
            - db
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        ports:
            - "3400:80"
        depends_on:
            - db
    node:
        image: node:current
        user: node
        working_dir: /assets
        volumes:
            - ./:/assets
        command: npm run watch
        depends_on:
            - php
    db:
        image: mysql:8
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_ROOT_HOST: "%"
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
            MYSQL_DATABASE: "${DB_DATABASE}"
        volumes:
            - mysqldata:/var/lib/mysql

volumes:
    mysqldata:
